
package org.killbill.billing.plugin.tahseel.cxf.com.ejada;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-08T11:41:29.142+03:00
 * Generated source version: 3.3.6
 *
 */
public final class BillManage_BillManageSOAP12_Client {

    private static final QName SERVICE_NAME = new QName("http://www.ejada.com", "BillManage");

    private BillManage_BillManageSOAP12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {

        URL wsdlURL = BillManage_Service.WSDL_LOCATION;

        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        BillManage_Service ss = new BillManage_Service(wsdlURL, SERVICE_NAME);
        BillManage port = ss.getBillManageSOAP12();

        {
        System.out.println("Invoking billManage...");
        BillManageRqType _billManage_billManageRq = null;
        BillManageRsType _billManage__return = port.billManage(_billManage_billManageRq);
        System.out.println("billManage.result=" + _billManage__return);


        }

        System.exit(0);
    }

}
