package com.ejada;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-08T11:41:29.472+03:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://www.ejada.com", name = "BillManage")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BillManage {

    @WebMethod(operationName = "BillManage", action = "BillManage")
    @WebResult(name = "BillManageRs", targetNamespace = "http://www.ejada.com", partName = "BillManageRs")
    public BillManageRsType billManage(

        @WebParam(partName = "BillManageRq", name = "BillManageRq", targetNamespace = "http://www.ejada.com")
        BillManageRqType billManageRq
    );
}
