/*
 * PaymentNotification
 * to notify about  the SADAD API  payment to tahseel-plugin
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.killbill.billing.plugin.tahseel.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.killbill.billing.plugin.tahseel.client.model.Item;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * ItemsWrapper
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-21T17:39:52.135Z")
public class ItemsWrapper extends HashMap<String, Object> {
  @SerializedName("Item")
  private Item item = null;

  public ItemsWrapper item(Item item) {
    this.item = item;
    return this;
  }

   /**
   * just to wrap around item
   * @return item
  **/
  @ApiModelProperty(required = true, value = "just to wrap around item")
  public Item getItem() {
    return item;
  }

  public void setItem(Item item) {
    this.item = item;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemsWrapper itemsWrapper = (ItemsWrapper) o;
    return Objects.equals(this.item, itemsWrapper.item) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(item, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemsWrapper {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    item: ").append(toIndentedString(item)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

