/*
 * PaymentNotification
 * to notify about  the SADAD API  payment to tahseel-plugin
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.killbill.billing.plugin.tahseel.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.killbill.billing.plugin.tahseel.client.model.PaymentMethodDetails;
import org.killbill.billing.plugin.tahseel.client.model.PayorPOI;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * Item
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-21T17:39:52.135Z")
public class Item extends HashMap<String, Object> {
  @SerializedName("AgencyCode")
  private String agencyCode = null;

  @SerializedName("IntermediatePaymentId")
  private String intermediatePaymentId = null;

  @SerializedName("BillCategory")
  private String billCategory = null;

  @SerializedName("BillAccount")
  private String billAccount = null;

  @SerializedName("PaymentAmount")
  private Double paymentAmount = null;

  @SerializedName("PaymentDate")
  private String paymentDate = null;

  /**
   * Gets or Sets paymentMethod
   */
  @JsonAdapter(PaymentMethodEnum.Adapter.class)
  public enum PaymentMethodEnum {
    SADAD("SADAD");

    private String value;

    PaymentMethodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PaymentMethodEnum fromValue(String text) {
      for (PaymentMethodEnum b : PaymentMethodEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<PaymentMethodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PaymentMethodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PaymentMethodEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return PaymentMethodEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("PaymentMethod")
  private PaymentMethodEnum paymentMethod = null;

  @SerializedName("PaymentMethodDetails")
  private PaymentMethodDetails paymentMethodDetails = null;

  @SerializedName("PaymentStatusCode")
  private String paymentStatusCode = null;

  @SerializedName("PayorPOI")
  private PayorPOI payorPOI = null;

  @SerializedName("PaymentReferenceInfo")
  private String paymentReferenceInfo = null;

  public Item agencyCode(String agencyCode) {
    this.agencyCode = agencyCode;
    return this;
  }

   /**
   * Get agencyCode
   * @return agencyCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getAgencyCode() {
    return agencyCode;
  }

  public void setAgencyCode(String agencyCode) {
    this.agencyCode = agencyCode;
  }

  public Item intermediatePaymentId(String intermediatePaymentId) {
    this.intermediatePaymentId = intermediatePaymentId;
    return this;
  }

   /**
   * Get intermediatePaymentId
   * @return intermediatePaymentId
  **/
  @ApiModelProperty(required = true, value = "")
  public String getIntermediatePaymentId() {
    return intermediatePaymentId;
  }

  public void setIntermediatePaymentId(String intermediatePaymentId) {
    this.intermediatePaymentId = intermediatePaymentId;
  }

  public Item billCategory(String billCategory) {
    this.billCategory = billCategory;
    return this;
  }

   /**
   * Get billCategory
   * @return billCategory
  **/
  @ApiModelProperty(required = true, value = "")
  public String getBillCategory() {
    return billCategory;
  }

  public void setBillCategory(String billCategory) {
    this.billCategory = billCategory;
  }

  public Item billAccount(String billAccount) {
    this.billAccount = billAccount;
    return this;
  }

   /**
   * Get billAccount
   * @return billAccount
  **/
  @ApiModelProperty(required = true, value = "")
  public String getBillAccount() {
    return billAccount;
  }

  public void setBillAccount(String billAccount) {
    this.billAccount = billAccount;
  }

  public Item paymentAmount(Double paymentAmount) {
    this.paymentAmount = paymentAmount;
    return this;
  }

   /**
   * Get paymentAmount
   * @return paymentAmount
  **/
  @ApiModelProperty(required = true, value = "")
  public Double getPaymentAmount() {
    return paymentAmount;
  }

  public void setPaymentAmount(Double paymentAmount) {
    this.paymentAmount = paymentAmount;
  }

  public Item paymentDate(String paymentDate) {
    this.paymentDate = paymentDate;
    return this;
  }

   /**
   * Get paymentDate
   * @return paymentDate
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPaymentDate() {
    return paymentDate;
  }

  public void setPaymentDate(String paymentDate) {
    this.paymentDate = paymentDate;
  }

  public Item paymentMethod(PaymentMethodEnum paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * Get paymentMethod
   * @return paymentMethod
  **/
  @ApiModelProperty(required = true, value = "")
  public PaymentMethodEnum getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(PaymentMethodEnum paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public Item paymentMethodDetails(PaymentMethodDetails paymentMethodDetails) {
    this.paymentMethodDetails = paymentMethodDetails;
    return this;
  }

   /**
   * Get paymentMethodDetails
   * @return paymentMethodDetails
  **/
  @ApiModelProperty(value = "")
  public PaymentMethodDetails getPaymentMethodDetails() {
    return paymentMethodDetails;
  }

  public void setPaymentMethodDetails(PaymentMethodDetails paymentMethodDetails) {
    this.paymentMethodDetails = paymentMethodDetails;
  }

  public Item paymentStatusCode(String paymentStatusCode) {
    this.paymentStatusCode = paymentStatusCode;
    return this;
  }

   /**
   * Get paymentStatusCode
   * @return paymentStatusCode
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPaymentStatusCode() {
    return paymentStatusCode;
  }

  public void setPaymentStatusCode(String paymentStatusCode) {
    this.paymentStatusCode = paymentStatusCode;
  }

  public Item payorPOI(PayorPOI payorPOI) {
    this.payorPOI = payorPOI;
    return this;
  }

   /**
   * Get payorPOI
   * @return payorPOI
  **/
  @ApiModelProperty(value = "")
  public PayorPOI getPayorPOI() {
    return payorPOI;
  }

  public void setPayorPOI(PayorPOI payorPOI) {
    this.payorPOI = payorPOI;
  }

  public Item paymentReferenceInfo(String paymentReferenceInfo) {
    this.paymentReferenceInfo = paymentReferenceInfo;
    return this;
  }

   /**
   * Get paymentReferenceInfo
   * @return paymentReferenceInfo
  **/
  @ApiModelProperty(value = "")
  public String getPaymentReferenceInfo() {
    return paymentReferenceInfo;
  }

  public void setPaymentReferenceInfo(String paymentReferenceInfo) {
    this.paymentReferenceInfo = paymentReferenceInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Item item = (Item) o;
    return Objects.equals(this.agencyCode, item.agencyCode) &&
        Objects.equals(this.intermediatePaymentId, item.intermediatePaymentId) &&
        Objects.equals(this.billCategory, item.billCategory) &&
        Objects.equals(this.billAccount, item.billAccount) &&
        Objects.equals(this.paymentAmount, item.paymentAmount) &&
        Objects.equals(this.paymentDate, item.paymentDate) &&
        Objects.equals(this.paymentMethod, item.paymentMethod) &&
        Objects.equals(this.paymentMethodDetails, item.paymentMethodDetails) &&
        Objects.equals(this.paymentStatusCode, item.paymentStatusCode) &&
        Objects.equals(this.payorPOI, item.payorPOI) &&
        Objects.equals(this.paymentReferenceInfo, item.paymentReferenceInfo) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agencyCode, intermediatePaymentId, billCategory, billAccount, paymentAmount, paymentDate, paymentMethod, paymentMethodDetails, paymentStatusCode, payorPOI, paymentReferenceInfo, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Item {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    agencyCode: ").append(toIndentedString(agencyCode)).append("\n");
    sb.append("    intermediatePaymentId: ").append(toIndentedString(intermediatePaymentId)).append("\n");
    sb.append("    billCategory: ").append(toIndentedString(billCategory)).append("\n");
    sb.append("    billAccount: ").append(toIndentedString(billAccount)).append("\n");
    sb.append("    paymentAmount: ").append(toIndentedString(paymentAmount)).append("\n");
    sb.append("    paymentDate: ").append(toIndentedString(paymentDate)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    paymentMethodDetails: ").append(toIndentedString(paymentMethodDetails)).append("\n");
    sb.append("    paymentStatusCode: ").append(toIndentedString(paymentStatusCode)).append("\n");
    sb.append("    payorPOI: ").append(toIndentedString(payorPOI)).append("\n");
    sb.append("    paymentReferenceInfo: ").append(toIndentedString(paymentReferenceInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

