/*
 * PaymentNotification
 * to notify about  the SADAD API  payment to tahseel-plugin
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.killbill.billing.plugin.tahseel.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/**
 * PaymentMethodDetails
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-21T17:39:52.135Z")
public class PaymentMethodDetails extends HashMap<String, Object> {
  @SerializedName("PaymentTransactionId")
  private String paymentTransactionId = null;

  @SerializedName("BankId")
  private String bankId = null;

  @SerializedName("BankPaymentId")
  private String bankPaymentId = null;

  @SerializedName("PaymentChannel")
  private String paymentChannel = null;

  public PaymentMethodDetails paymentTransactionId(String paymentTransactionId) {
    this.paymentTransactionId = paymentTransactionId;
    return this;
  }

   /**
   * Get paymentTransactionId
   * @return paymentTransactionId
  **/
  @ApiModelProperty(example = "3238381513", required = true, value = "")
  public String getPaymentTransactionId() {
    return paymentTransactionId;
  }

  public void setPaymentTransactionId(String paymentTransactionId) {
    this.paymentTransactionId = paymentTransactionId;
  }

  public PaymentMethodDetails bankId(String bankId) {
    this.bankId = bankId;
    return this;
  }

   /**
   * Get bankId
   * @return bankId
  **/
  @ApiModelProperty(example = "NCBKSAJE", value = "")
  public String getBankId() {
    return bankId;
  }

  public void setBankId(String bankId) {
    this.bankId = bankId;
  }

  public PaymentMethodDetails bankPaymentId(String bankPaymentId) {
    this.bankPaymentId = bankPaymentId;
    return this;
  }

   /**
   * Get bankPaymentId
   * @return bankPaymentId
  **/
  @ApiModelProperty(example = "20200108-152358-103152923", value = "")
  public String getBankPaymentId() {
    return bankPaymentId;
  }

  public void setBankPaymentId(String bankPaymentId) {
    this.bankPaymentId = bankPaymentId;
  }

  public PaymentMethodDetails paymentChannel(String paymentChannel) {
    this.paymentChannel = paymentChannel;
    return this;
  }

   /**
   * Get paymentChannel
   * @return paymentChannel
  **/
  @ApiModelProperty(example = "CORP", value = "")
  public String getPaymentChannel() {
    return paymentChannel;
  }

  public void setPaymentChannel(String paymentChannel) {
    this.paymentChannel = paymentChannel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentMethodDetails paymentMethodDetails = (PaymentMethodDetails) o;
    return Objects.equals(this.paymentTransactionId, paymentMethodDetails.paymentTransactionId) &&
        Objects.equals(this.bankId, paymentMethodDetails.bankId) &&
        Objects.equals(this.bankPaymentId, paymentMethodDetails.bankPaymentId) &&
        Objects.equals(this.paymentChannel, paymentMethodDetails.paymentChannel) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentTransactionId, bankId, bankPaymentId, paymentChannel, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethodDetails {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    paymentTransactionId: ").append(toIndentedString(paymentTransactionId)).append("\n");
    sb.append("    bankId: ").append(toIndentedString(bankId)).append("\n");
    sb.append("    bankPaymentId: ").append(toIndentedString(bankPaymentId)).append("\n");
    sb.append("    paymentChannel: ").append(toIndentedString(paymentChannel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

